question_data = [{"type": "boolean", "difficulty": "medium", "category": "History",
                  "question": "The two atomic bombs dropped on Japan by the United States in August 1945 were named Little Man and Fat Boy.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Science: Mathematics",
                  "question": "The set of all algebraic numbers is countable.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Science: Computers",
                  "question": "The open source program Redis is a relational database server.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Video Games",
                  "question": "In Resident Evil, only Chris has access to the grenade launcher.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Cartoon &amp; Animations",
                  "question": "Donald Duck played the role of Bob Cratchit in Disneys 1983 adaptation of A Christmas Carol.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
                  "question": "When BMW was established in 1916, it was producing automobiles.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Video Games",
                  "question": "Pistons were added to Minecraft in Beta 1.5.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Video Games",
                  "question": "Mortal Kombat was almost based on Jean-Claude Van Damme movie.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Music",
                  "question": "Twenty One Pilots made the song The Motion featuring Sampha.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "General Knowledge",
                  "question": "Santa Claus is a variety of melon.",
                  "correct_answer": "True", "incorrect_answers": ["False"]}]
# Got these from Open Trivia DB API